language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - 7.0
  - 7.1
  - nightly

matrix:
  allow_failures:
    - php: 5.4
    - php: hhvm
    - php: nightly

before_script :
  - composer install --dev

script:
  - ./vendor/bin/phpcs --warning-severity=6 --standard=PSR2 *.php tests
  - ./vendor/bin/phpunit

notifications:
  email:
    - matthew@baggett.me
